const fs = require("fs");

const seats = "C".repeat(43);

fs.writeFile("res.txt", seats, (err) => {
  if (err) throw err;
  console.log("The file has been saved!");
});

const charter = 
  "_________CCCCCCCC__CCCCCCCCCCC_CCCCCCCCCC__CCCCCCCCCC________/" + "";
  "________CCCCCCCCC__CCCCCCCCCCC_CCCCCCCCCC__CCCCCCCCCC________/" + "";
  "_______CCCCCCCCCC__CCCCCCCCCCC_CCCCCCCCCC__CCCCCCCCCCC_______/" + "";
  "______CCCCCCCCCCC__CCCCCCCCCCC_CCCCCCCCCC__CCCCCCCCCCC_______/" + "";

const stall =
  "_____SSSSSSSSSSSS__SSSSSSSSSSS_SSSSSSSSSSS__SSSSSSSSSSSS_____/" +
  "_____SSSSSSSSSSSS__SSSSSSSSSSS_SSSSSSSSSSS__SSSSSSSSSSSS_____/" +
  "____SSSSSSSSSSSS__SSSSSSSSSSSS_SSSSSSSSSSS__SSSSSSSSSSSS_____/" +
  "___SSSSSSSSSSSSS__SSSSSSSSSSSS_SSSSSSSSSSSS__SSSSSSSSSSSSS___/" +
  "___SSSSSSSSSSSSS__SSSSSSSSSSSS_SSSSSSSSSSSS__SSSSSSSSSSSSS___/" +
  "__SSSSSSSSSSSSS__SSSSSSSSSSSSS_SSSSSSSSSSSS__SSSSSSSSSSSSS___/" +
  "___SSSSSSSSSSSSS__SSSSSSSSSSSS_SSSSSSSSSSSS__SSSSSSSSSSSSS___/";

const balcony =
  "___BBBBBBBBBBBBB__BBBBBBBBBBBB_BBBBBBBBBBBB__BBBBBBBBBBBBB___/" +
  "___BBBBBBBBBBBBB__BBBBBBBBBBBB_BBBBBBBBBBBB__BBBBBBBBBBBBB___/" +
  "__BBBBBBBBBBBBB__BBBBBBBBBBBBB_BBBBBBBBBBBBB__BBBBBBBBBBBBB__/" +
  "_BBBBBBBBBBBBBB__BBBBBBBBBBBBB_BBBBBBBBBBBBB__BBBBBBBBBBBBBB_/" +
  "__BBBBBBBBBBBBB__BBBBBBBBBBBBB_BBBBBBBBBBBBB__BBBBBBBBBBBBB__/";
